[package]
name = "first-nannou-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.19"
imageproc = "0.24"
ab_glyph = "0.2.24"